/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Encode a varint value to a Buffer */
export declare function encodeVarint(value: number): Buffer
/**
 * Decode a varint from a buffer at the given position
 * Returns an object with { value, length }
 */
export interface VarintResult {
  value: number
  length: number
}
export declare function decodeVarint(buffer: Buffer, pos: number): VarintResult
/** Binary reader for Protocol Buffer messages */
export declare class Reader {
  /** Create a new Reader from a Buffer or Uint8Array */
  constructor(buffer: Buffer)
  /** Read uint32 (varint decoded) */
  uint32(): number
  /** Read int32 (varint decoded) */
  int32(): number
  /** Read sint32 (zigzag decoded) */
  sint32(): number
  /** Read uint64 (varint decoded) */
  uint64(): number
  /** Read int64 (varint decoded) */
  int64(): number
  /** Read sint64 (zigzag decoded) */
  sint64(): number
  /** Read bool (varint decoded) */
  bool(): boolean
  /** Read fixed32 (little-endian 4 bytes) */
  fixed32(): number
  /** Read sfixed32 (little-endian 4 bytes) */
  sfixed32(): number
  /** Read fixed64 (little-endian 8 bytes) */
  fixed64(): number
  /** Read sfixed64 (little-endian 8 bytes) */
  sfixed64(): number
  /** Read float (32-bit, little-endian) */
  float(): number
  /** Read double (64-bit, little-endian) */
  double(): number
  /** Read bytes (length-delimited) */
  bytes(): Buffer
  /** Read string (UTF-8, length-delimited) */
  string(): string
  /** Skip a specific number of bytes */
  skip(length: number): this
  /** Skip a field based on wire type */
  skipType(wireType: number): this
  /** Get current position */
  pos(): number
}
/** Binary writer for Protocol Buffer messages with fluent API */
export declare class Writer {
  /** Create a new Writer */
  constructor()
  /** Write uint32 (varint encoded) */
  uint32(value: number): this
  /** Write int32 (varint encoded) */
  int32(value: number): this
  /** Write sint32 (zigzag + varint encoded) */
  sint32(value: number): this
  /** Write uint64 (varint encoded) */
  uint64(value: number): this
  /** Write int64 (varint encoded) */
  int64(value: number): this
  /** Write sint64 (zigzag + varint encoded) */
  sint64(value: number): this
  /** Write bool (varint encoded as 0 or 1) */
  bool(value: boolean): this
  /** Write fixed32 (little-endian 4 bytes) */
  fixed32(value: number): this
  /** Write sfixed32 (little-endian 4 bytes) */
  sfixed32(value: number): this
  /** Write fixed64 (little-endian 8 bytes) */
  fixed64(value: number): this
  /** Write sfixed64 (little-endian 8 bytes) */
  sfixed64(value: number): this
  /** Write float (32-bit, little-endian) */
  float(value: number): this
  /** Write double (64-bit, little-endian) */
  double(value: number): this
  /** Write bytes (length-delimited) */
  bytes(value: Buffer): this
  /** Write string (UTF-8, length-delimited) */
  string(value: string): this
  /**
   * Fork the writer for nested messages
   * Returns the position for later length calculation
   */
  fork(): number
  /**
   * Write length delimiter after fork
   * Calculates the length of the nested message and updates the length prefix
   */
  ldelim(): this
  /** Finish writing and return the buffer */
  finish(): Buffer
  /** Reset the writer to reuse it */
  reset(): this
}
